import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WDD430 Team 7 Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
<Toaster
  position="top-center"
  reverseOrder={false}
  toastOptions={{
    style: {
      background: "rgba(255, 255, 255, 0.1)",
      color: "#fff",
      backdropFilter: "blur(12px)",
      WebkitBackdropFilter: "blur(12px)",
      borderRadius: "12px",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      padding: "12px 18px",
      fontSize: "15px",
      fontWeight: "500",
      boxShadow: "0 4px 30px rgba(0, 0, 0, 0.2)",
    },
    success: {
      style: {
        background: "rgba(34, 197, 94, 0.15)", 
        border: "1px solid rgba(34, 197, 94, 0.4)",
        color: "#bbf7d0",
      },
      iconTheme: {
        primary: "#22c55e",
        secondary: "#fff",
      },
    },
    error: {
      style: {
        background: "rgba(239, 68, 68, 0.15)", 
        border: "1px solid rgba(239, 68, 68, 0.4)",
        color: "#fecaca",
      },
      iconTheme: {
        primary: "#ef4444",
        secondary: "#fff",
      },
    },
  }}
/>

      </body>
    </html>
  );
}
